name: action-gh-release
# https://github.com/softprops/action-gh-release

on: push

jobs:
  build:
    permissions:
      contents: write
      pull-requests: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
