name: Changelog CI

on:
  workflow_dispatch:

  pull_request:
    types: [ opened ]
    branches:
      - version-bump

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Get Current Version
        id: version
        run: | 
          echo "version=$(<VERSION)" >> $GITHUB_OUTPUT
      - name: Print Version Name
        run: echo "release version ${{steps.version.outputs.version}}"
  
      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          release_version: "${{steps.version.outputs.version}}"