name: create-github-releases-based-on-changelog
# https://github.com/marketplace/actions/create-github-releases-based-on-changelog
permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version name'
        required: true
        default: 'minor'
        type: choice
        options:
        - major
        - minor
        - patch
  # push:
  #   tags:
  #     - "[0-9]+.*"

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          # (Optional) Path to changelog.
          changelog: CHANGELOG.md
          allow-missing-changelog: true
          # (Required) GitHub token for creating GitHub Releases.
          branch: main
          token: ${{ secrets.GITHUB_TOKEN }}