name: My Version

on: 
  workflow_dispatch:
    inputs:

  # push:
  #   tags:
  #     - '*.*.*'

jobs:
  build:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: My Script
        id: new_version
        run: ./scripts/create-release.sh
      - name: Create Tag
        uses: actions/github-script@v7
        id: create_tag
        with: 
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'ref/tags/${{ steps.new_version.outputs.version}}',
              sha: context.sha
            })

      # - name: Create Tag
      #   run: |
      #     git tag $VERSION
      #     git push --follow-tags
      # - name: Create release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ steps.get_tag.outputs.version }}
      #     release_name: Release ${{ steps.get_tag.outputs.version }}
      #     body_path: ./release_notes.md
      #     draft: false
      #     prerelease: false
          
      # generate changelog 
      # update tag



