name: Github-Release-Action
# https://github.com/elgohr/Github-Release-Action
on: 
  push:
    tags:
      - 'v*'

jobs:
  build:
    permissions:
      contents: write
      pull-requests: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Createa Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with: 
          title: "some title goes here!!!"
