name: Release
# https://github.com/marketplace/actions/create-github-releases-based-on-changelog
permissions:
  contents: write

on:
  push:
    tags:
      - "([0-9]\\d*)\\.([0-9]\\d*)\\.([0-9]\\d*)"

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          # (Optional) Path to changelog.
          changelog: CHANGELOG.md
          # (Required) GitHub token for creating GitHub Releases.
          branch: main
          token: ${{ secrets.GITHUB_TOKEN }}