name: Bump Version
on:
  workflow_dispatch:
    inputs:
      bump-mode:
        description: 'Select bump mode'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

  push:
    branches: [main]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Retrieve New Version
        run: bash ./.ci_steps/bump.sh ${{inputs.bump-mode}}
        id: bump

      - name: 'Checkout version-bump branch'
        run: |
          git fetch origin version-bump
          git checkout version-bump
        
      - name: Fetch Current Branch
        id: current_branch
        run: echo "current_branch=$(git branch --show-current)" >> $GITHUB_OUTPUT
  
      - name: Verify Current Branch
        if: ${{steps.current_branch.outputs.current_branch != 'version-bump'}}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Current branch is not version-bump')

      - name: Update Version to version-bump Branch
        run: echo "${{steps.bump.outputs.NEW_VERSION}}" > VERSION 

      - name: Print Bump Results
        run: |
          echo "New Version: ${{steps.bump.outputs.NEW_VERSION}}"

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: version-bump
          commit_message: "Bump version from ${{steps.bump.outputs.OLD_VERSION}} to ${{steps.bump.outputs.NEW_VERSION}} [skip ci]"
          commit_user_name: ${{github.actor}}
          commit_user_email: "${{github.actor}}@users.noreply.github.com"
          file_pattern: VERSION
      
      # - name: Update CHANGELOG
      #   id: changelog
      #   uses: requarks/changelog-action@v1
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     fromTag: '0.1.20'
      #     toTag: '0.1.17'

      # - name: Changelog
      #   uses: ncipollo/release-action@v1.12.0
      #   with:
      #     name: 'refs/tags/0.1.17'
      #     body: ${{ steps.changelog.outputs.changes }}
      #     token: ${{ secrets.GITHUB_TOKEN }}





      # - name: Create pull request
      #   id: create_pr
      #   uses: peter-evans/create-pull-request@v5
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: version-bump
      #     title: "Release: ${{steps.bump.outputs.NEW_VERSION}}"
      #     commit-message: "Release: ${{steps.bump.outputs.NEW_VERSION}}"
      #     body: ""
      #     base: main
  