name: Bump Version
on:
  workflow_dispatch:
    inputs:
      bump-mode:
        description: 'Select bump mode'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

  # push:
  #   branches: [main]

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Retrieve New Version
        run: bash ./.ci_steps/bump.sh ${{inputs.bump-mode}}
        id: bump

      - name: 'Checkout version-bump branch'
        run: |
          git fetch origin version-bump
          git checkout version-bump
        
      - name: Print Current Branch
        id: current_branch
        run: echo "current_branch=$(git branch --show-current)" >> $GITHUB_OUTPUT
  
      - name: Verify Current Branch
        if: ${{steps.current_branch.outputs.current_branch != 'version-bump'}}
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('Current branch is not version-bump')

      - name: Update Version to version-bump Branch
        id: update
        run: bash ./.ci_steps/update-version.sh ${{steps.bump.outputs.OLD_VERSION}} ${{steps.bump.outputs.NEW_VERSION}}
        
      - name: Print Bump Results
        run: |
          echo "New Version: ${{steps.update.outputs.CURRENT_VERSION}}"

      - name: "Complex Configuration"
        id: build_changelog
        if: startsWith(github.ref, 'refs/tags/')
        uses: mikepenz/release-changelog-builder-action@v4
        with:
          # configuration: "configuration_complex.json"
          fromTag: ${{steps.bump.outputs.OLD_VERSION}}
          toTag: ${{steps.bump.outputs.NEW_VERSION}}
          token: ${{ secrets.GITHUB_TOKEN }}
          
      # - name: Create pull request
      #   id: create_pr
      #   uses: peter-evans/create-pull-request@v5
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: version-bump
      #     title: "Release: ${{steps.bump.outputs.NEW_VERSION}}"
      #     commit-message: "Release: ${{steps.bump.outputs.NEW_VERSION}}"
      #     body: ""
      #     base: main
  